//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercice_Gestion_Liver
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liver
    {
        public int ID { get; set; }
        public string Titre { get; set; }
        public string Ecrivain { get; set; }
        public System.DateTime DateSortie { get; set; }
        public double Prix { get; set; }
    }
}
